Feat/multiple databases
Snowflake-Labs/sqltools-snowflake-driver pull request #58
Opened 2022-11-05 06:39 UTC by adamNewell

Some users have multiple databases available to them on a single account. It is often necessary to interact with them within the same context, therefore it makes sense to include them all within the same connection

2022-11-05 12:01 UTC, koszti requested changes

2022-11-05 12:01 UTC, koszti commented on src/ls/driver.ts
> +    console.log(dbList);
can you please remove this line?

2022-11-08 23:03 UTC, merged

2022-11-08 23:05 UTC, koszti commented
thanks for the PR. Wdyt, should we release this separately or better to do it together with your other PR? https://github.com/Snowflake-Labs/sqltools-snowflake-driver/pull/59

2022-11-09 05:39 UTC, adamNewell commented
These PRs were designed to be able to be released separately, but I don't see the need. They are both part of navigation/visibility and will resolve a few of the issues logged for the repo. My only overall concern is getting an opinion on iconography for the various object types. I attempted to match icons where I could based on [#14](https://github.com/Snowflake-Labs/sqltools-snowflake-driver/issues/14), but not all were available via codicon